### ISSUE TITLE
Project does not compile in Rust 1.85 edition 2024

### ISSUE THREAD

**Issue by Havunen** [twitchax/axum-insights#2]
steps to reproduce: 

add following to Cargo.toml
```
edition = "2024"
rust-version = "1.85.0"
```

and compile:

```rust
error[E0277]: the trait bound `!: IntoResponse` is not satisfied
    --> src/lib.rs:1236:34
     |
1236 |             .route("/fail2", get(|| async { panic!("panic") }))
     |                              --- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `IntoResponse` is not implemented for `!`
     |                              |
     |                              required by a bound introduced by this call
     |
     = help: the following other types implement trait `IntoResponse`:
               &'static [u8; N]
               &'static [u8]
               &'static str
               ()
               (R,)
               (StatusCode, R)
               (StatusCode, T1, R)
               (StatusCode, T1, T2, R)
             and 121 others
     = note: this error might have been caused by changes to Rust's type-inference algorithm (see issue #48950 <https://github.com/rust-lang/rust/issues/48950> for more information)
     = help: did you intend to use the type `()` here instead?
     = note: required for `{closure@src/lib.rs:1236:34: 1236:36}` to implement `Handler<((),), ()>`
note: required by a bound in `axum::routing::get`
    --> /.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/axum-0.8.1/src/routing/method_routing.rs:440:1
     |
440  | top_level_handler_fn!(get, GET);
     | ^^^^^^^^^^^^^^^^^^^^^^---^^^^^^
     | |                     |
     | |                     required by a bound in this function
     | required by this bound in `get`
     = note: this error originates in the macro `top_level_handler_fn` (in Nightly builds, run with -Z macro-backtrace for more info)


```

**Comment by Havunen** [comment]
Its actually related to axum: https://github.com/tokio-rs/axum/issues/3169
